// Recording script for training a personal voice. Varied lengths, statements, questions and
// exclamations, numbers written as words, and the vocabulary the assistant actually speaks
// (projects, tech terms, client conversations), with everyday sentences for natural rhythm.
// About 420 lines, roughly 35 minutes of speech.

export const SENTENCES: string[] = [
  // Introductions and greetings
  "Hi, I'm Ahmad Farooq, a full stack developer focused on AI and automation.",
  "Thanks for stopping by. What would you like to build?",
  "Hello! It's great to meet you.",
  "Welcome. Tell me a little about your project.",
  "Good morning, and thank you for reaching out.",
  "Good evening. How has your day been so far?",
  "I'm based in Haripur, Pakistan, and I work remotely with clients around the world.",
  "I've been building software professionally for more than five years.",
  "I've delivered over fifty projects for more than thirty clients.",
  "Every client so far has been happy with the result, and I intend to keep it that way.",
  "Nice to hear from you again.",
  "It's a pleasure to work with you.",
  "Let me introduce myself properly.",
  "I usually start by listening, then I ask a few questions.",
  "Feel free to interrupt me at any time.",

  // Asking about the client's idea
  "What problem are you trying to solve?",
  "Who will use this product every day?",
  "Do you need a mobile app, a website, or both?",
  "When would you like the first version to be ready?",
  "Have you already built anything, or are we starting from scratch?",
  "What does success look like for you in three months?",
  "Is this for your own business, or for a client of yours?",
  "Which part of the process takes your team the most time?",
  "Do you already have a design, or should I help with that too?",
  "How many people do you expect to use it in the first year?",
  "Would you like it to work offline as well?",
  "Are there any tools your team already relies on?",
  "Should the app support English only, or other languages too?",
  "What would you change first if you could change only one thing?",
  "Can you walk me through a typical day for your users?",
  "Is there a deadline we absolutely have to meet?",
  "Which features are essential, and which are nice to have?",
  "Do you have a budget range in mind?",
  "Who on your team will I be working with?",
  "How do you handle this task today?",

  // Explaining an approach
  "Let's start small and build the simplest version that works.",
  "I'd suggest launching with three core features and adding more later.",
  "We can test the idea quickly before investing in the full product.",
  "First, we'll agree on the scope. Then I'll share a short plan.",
  "I'll send you a working demo at the end of each week.",
  "That way you can give feedback early, while changes are still cheap.",
  "We'll keep the design clean, fast and easy to use.",
  "I'll write down every decision so nothing gets lost.",
  "Once the first version is live, we'll measure what people actually use.",
  "If something isn't working, we'll find out quickly and fix it.",
  "The backend will run on Node.js, with a database in Supabase.",
  "For the mobile app, Flutter lets us ship to Android and iPhone from one codebase.",
  "React Native is another good option if your team already knows React.",
  "We can host the website on Vercel, so it's fast everywhere.",
  "Payments can go through Stripe, or local options like JazzCash and Easypaisa.",
  "I'll set up monitoring, so we hear about problems before your users do.",
  "Security matters, so passwords and keys never live in the code.",
  "We'll keep your data in your own accounts, so you always stay in control.",
  "The admin panel will let your team manage users without calling me.",
  "Automation can take care of the repetitive work your team does by hand.",

  // AI and automation
  "I build AI assistants, voice agents and retrieval augmented generation systems.",
  "An AI assistant can answer customer questions at any time of day.",
  "A voice agent listens, thinks, and replies out loud, just like this.",
  "Retrieval augmented generation lets the AI answer from your own documents.",
  "The assistant quotes its sources, so you can check every answer.",
  "I work with OpenAI, Claude and Google Gemini.",
  "Embeddings turn text into numbers that capture its meaning.",
  "We store those embeddings in a vector database such as Pinecone.",
  "Prompt design is about giving the model clear instructions and good examples.",
  "I always review AI output carefully before it reaches your customers.",
  "The model should never invent facts. If it doesn't know, it should say so.",
  "AI works best when it handles the routine questions and people handle the rest.",
  "We can connect the assistant to Slack, WhatsApp or your website.",
  "Agentic workflows let the AI take several steps on its own.",
  "With MCP servers, Claude can use tools like search and spreadsheets.",
  "Automation can sync your orders, update inventory and send reports every morning.",
  "Instead of copying data between systems, a small script can do it every hour.",
  "The bot reads the contract and pulls out the key dates and obligations.",
  "It can add every deadline to your Google Calendar with one click.",
  "Streaming means the reply starts appearing before it's even finished.",

  // Projects
  "Parlor is a voice app where you create AI personalities and talk to them.",
  "You're actually talking to me through Parlor right now.",
  "Each personality has its own name, behaviour and voice.",
  "My legal document assistant lives inside Slack.",
  "You drop a contract into a channel, and it reads it in seconds.",
  "Then you can ask questions and get answers with sources.",
  "Zyro Cloud brings orders from Shopify, Daraz and WooCommerce into one dashboard.",
  "The hardest part was keeping inventory consistent across three marketplaces.",
  "Zyro Cloud also sends WhatsApp messages automatically when an order changes.",
  "RouteBuddy is a carpooling app that's live on Google Play.",
  "Riders can bid on fares, and drivers can accept the best offer.",
  "RouteBuddy even has an assistant that understands Roman Urdu.",
  "BuddyCart is an online store that posts new products to Facebook and Instagram automatically.",
  "The Enterprise CRM gives sales teams AI insights about their customers.",
  "I'm currently building an AI pipeline that finds new startups and drafts outreach.",
  "Shortify uses Gemini to summarise long articles in seconds.",
  "Kardly creates print ready business cards from simple templates.",
  "Dukan e Khata is a digital ledger that works even without internet.",
  "HomeHaven lets people book properties and pay online.",
  "SkillBuddy connects skilled workers with clients nearby.",

  // Process, timelines and pricing (no figures)
  "The price depends on the scope, so let's agree on that first.",
  "I can give you a clear estimate once I understand the features.",
  "Most first versions take a few weeks, not months.",
  "I'd rather give you a realistic date than an optimistic one.",
  "If anything changes, I'll tell you straight away.",
  "We'll split the work into small milestones you can review.",
  "You'll always know what I'm working on and what comes next.",
  "Communication is just as important as the code.",
  "I'm happy to work across time zones.",
  "Send me an email and we'll set up a short call.",
  "You can also message me on WhatsApp.",
  "My email is ahmad farooq five five eight one at gmail dot com.",
  "My portfolio has more examples of my work.",
  "You'll find my code on GitHub as well.",
  "Let's schedule a call for next week, if that suits you.",

  // Technical explanations
  "An API is simply a way for two programs to talk to each other.",
  "The database keeps your information safe and organised.",
  "Caching makes the app feel much faster.",
  "We'll write tests, so new features don't break old ones.",
  "Version control means we can always go back to an earlier state.",
  "Push notifications remind users when something important happens.",
  "The map shows each driver's position in real time.",
  "Offline support means the app still works on a weak connection.",
  "Sign in with Google is quick and secure.",
  "Rate limiting stops anyone from overloading the system.",
  "Webhooks let other services tell us the moment something changes.",
  "The server sends the reply in small pieces as it's generated.",
  "We'll compress the images, so pages load quickly on mobile data.",
  "A responsive layout adapts to phones, tablets and large screens.",
  "Clean architecture keeps the code easy to change later.",
  "Code reviews catch mistakes before they reach production.",
  "Good logging tells us exactly what went wrong and when.",
  "Backups run automatically every night.",
  "Performance matters, especially on older Android phones.",
  "The app starts in under two seconds, even on modest devices.",

  // Numbers, dates and times written out
  "The meeting is on Monday at ten in the morning.",
  "We launched the first version on the fifteenth of March.",
  "The app has more than twelve thousand users.",
  "It took us about three weeks to build the prototype.",
  "Please reply before the twentieth of November.",
  "The report runs at six o'clock every evening.",
  "There are seven days left until the deadline.",
  "We reduced the loading time by almost half.",
  "The file is about two megabytes.",
  "I started freelancing in two thousand nineteen.",
  "My first mobile job began in January two thousand twenty one.",
  "The renewal notice is due thirty days before the first of June.",
  "Ninety nine percent of requests finish in under a second.",
  "We have four hundred and fifty products in the catalogue.",
  "The call lasted about forty five minutes.",
  "One, two, three, four, five, six, seven, eight, nine, ten.",
  "Eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen.",
  "Twenty, thirty, forty, fifty, sixty, seventy, eighty, ninety, one hundred.",
  "First, second, third, fourth and fifth.",
  "It's half past three on a Thursday afternoon.",

  // Friendly conversation and reactions
  "That's a great idea!",
  "I love that question.",
  "Absolutely, we can do that.",
  "That makes a lot of sense.",
  "Interesting. Tell me more about that.",
  "I see what you mean.",
  "Good point. I hadn't thought of it that way.",
  "Don't worry, we'll figure it out together.",
  "No problem at all.",
  "That's completely fine.",
  "Sounds good to me.",
  "Let me think about that for a second.",
  "Honestly, I'd keep it simpler.",
  "Wow, that's impressive!",
  "Really? I didn't know that.",
  "Of course, happy to help.",
  "Thanks, I appreciate that.",
  "Sorry, could you say that again?",
  "I'm not sure yet, but I'll find out.",
  "Exactly, that's what I was thinking.",
  "Fair enough.",
  "Right, let's move on to the next part.",
  "Perfect, that's all I needed.",
  "Hmm, that might be tricky, but it's possible.",
  "You're right, that would be better.",
  "Great, I'll get started today.",
  "That's a wrap for today. Talk soon!",
  "Take care, and have a wonderful day.",
  "It was lovely talking to you.",
  "See you next week.",

  // Everyday sentences for natural rhythm and sound coverage
  "The morning sun came through the window and warmed the kitchen.",
  "She poured two cups of tea and sat down by the garden.",
  "The train was late, so we walked the rest of the way.",
  "My brother bought a new bicycle last summer.",
  "The children laughed as the kite rose above the trees.",
  "A cold wind blew across the quiet valley.",
  "We watched the rain from the porch until it stopped.",
  "The library closes early on Fridays.",
  "He fixed the broken chair with a few nails and some glue.",
  "The market was busy with people buying fresh vegetables.",
  "Please close the door quietly when you leave.",
  "The mountains looked blue in the evening light.",
  "Our neighbour grows tomatoes, peppers and mint.",
  "The old clock on the wall stopped at midnight.",
  "I usually go for a short walk after dinner.",
  "The bread smelled wonderful as it came out of the oven.",
  "They painted the fence white over the weekend.",
  "A small dog followed us all the way home.",
  "The river was calm and clear this morning.",
  "Could you pass me the salt, please?",
  "The museum has a new exhibition on ancient maps.",
  "We stayed up late talking about the future.",
  "The phone rang just as I was falling asleep.",
  "Fresh oranges are sweetest in the winter.",
  "The bus stops right in front of the school.",
  "He reads a few pages of a book every night.",
  "The roof leaked during the storm last year.",
  "She speaks three languages fluently.",
  "The football match ended in a draw.",
  "My grandmother tells the best stories.",
  "The streets were empty early on Sunday.",
  "We planted a lemon tree in the yard.",
  "A cup of coffee helps me focus in the morning.",
  "The airport was crowded before the holidays.",
  "He wore a blue jacket and brown shoes.",
  "The lights flickered and then went out.",
  "Thick clouds gathered over the hills.",
  "Let's meet at the cafe near the bridge.",
  "The teacher wrote the answer on the board.",
  "Birds were singing before the sun came up.",
  "The cat jumped onto the shelf and knocked over a vase.",
  "We need eggs, milk, rice and a little sugar.",
  "The festival lit up the whole town.",
  "Rain is expected later in the week.",
  "His handwriting is very neat.",
  "The road winds slowly up the mountain.",
  "Somebody left an umbrella on the train.",
  "Fresh paint dries faster in warm weather.",
  "The garden looks beautiful in spring.",
  "Which way is the nearest station?",

  // Questions and intonation
  "Are you ready to begin?",
  "Would you prefer a call or an email?",
  "Isn't that exactly what we wanted?",
  "Why do you think users leave so early?",
  "How long have you been running the business?",
  "Where are most of your customers based?",
  "Can we make it even simpler?",
  "Did the new version fix the problem?",
  "What if we tried a different approach?",
  "Shall we look at the design together?",
  "Is everything clear so far?",
  "Do you have any questions for me?",
  "Would Tuesday or Wednesday work better for you?",
  "Have you tested it on an older phone?",
  "Should we add a dark mode?",
  "What happens if the payment fails?",
  "Who should receive the daily report?",
  "How did you hear about me?",
  "Would you like me to prepare a short proposal?",
  "Does that answer your question?",

  // Longer, flowing sentences
  "If you're thinking about adding AI to your product, I'd love to hear what you have in mind.",
  "The goal isn't to use AI everywhere, but to use it where it saves real time for real people.",
  "When the first version is live, we'll watch how people use it and improve the parts that matter most.",
  "A good product feels simple to the user, even when there's a lot happening behind the scenes.",
  "I enjoy taking an idea from the first conversation all the way to launch and beyond.",
  "Most of my clients come back for a second project, which tells me we're doing something right.",
  "If a feature doesn't help your users, it's usually better to leave it out.",
  "Small, frequent releases are safer than one big launch at the end.",
  "The assistant can answer questions about your products, your policies and your opening hours.",
  "Behind every quick answer is a lot of careful work on data, prompts and testing.",
  "Once your team trusts the system, they'll find new ways to use it that we never planned.",
  "I'd rather build something small that works perfectly than something big that almost works.",
  "Good software respects people's time, their privacy and their patience.",
  "We can start with a two week trial, then decide together how to continue.",
  "Let me summarise what we've agreed, so we're both on the same page.",

  // Mixed sound coverage
  "Thirty three thin thieves thought they thrilled the throne.",
  "She sells sea shells by the sea shore.",
  "Peter picked a peck of pickled peppers.",
  "The quick brown fox jumps over the lazy dog.",
  "Unique New York, unique New York.",
  "Red lorry, yellow lorry.",
  "Which witch wished which wicked wish?",
  "Freshly fried flying fish.",
  "A big black bug bit a big black bear.",
  "Six slippery snails slid slowly seaward.",
  "Measure the pleasure of a treasure.",
  "The vision was unusual and the decision was casual.",
  "Judge the edge of the bridge.",
  "Choose the cheese and chew it slowly.",
  "Thank you for thinking of three things this Thursday.",
  "Whether the weather is warm or whether the weather is cold.",
  "Rolling rivers run around rugged rocks.",
  "Lucky lizards love leaping over logs.",
  "Very vivid violets grow in the valley.",
  "Zebras zigzag across the dusty zone.",

  // Assistant style replies
  "Here's what I'd suggest.",
  "There are two ways to approach this.",
  "The short answer is yes.",
  "The honest answer is, it depends.",
  "Let me explain how it works.",
  "In simple terms, the app does three things.",
  "The main benefit is that it saves your team time.",
  "The biggest risk is unclear requirements, so let's avoid that.",
  "I'd recommend starting with the mobile app.",
  "I'd recommend starting with a simple website first.",
  "That's something I've built before, so I know the pitfalls.",
  "We could use an existing tool for that, instead of building it.",
  "This part is quick. The tricky part is the integration.",
  "It's possible, but it would take a little longer.",
  "I don't have the details on that, but I'm happy to discuss it directly.",
  "Let's keep that for the second version.",
  "Good news: that's already supported.",
  "Unfortunately, that service doesn't allow it.",
  "We'll handle that automatically, so nobody has to remember.",
  "Once it's set up, it just runs in the background.",

  // Emotions and emphasis
  "I'm really excited about this project!",
  "This is genuinely one of my favourite parts of the job.",
  "I'm sorry about the delay. It won't happen again.",
  "Congratulations on the launch!",
  "That was a tough bug, but we found it.",
  "I'm proud of how this turned out.",
  "It's frustrating when tools don't talk to each other.",
  "Relax, everything is backed up.",
  "This is important, so let's take our time.",
  "Great work, everyone.",
  "Well, that was unexpected!",
  "I can't wait to show you the demo.",
  "We're almost there.",
  "Finally, it works!",
  "Let's celebrate this one.",

  // More client conversation
  "Could you share a few examples of apps you like?",
  "I'll prepare a short document with the plan and the timeline.",
  "Let's keep the first meeting to thirty minutes.",
  "You'll own the code and all of the accounts.",
  "I'll hand everything over with clear documentation.",
  "After launch, I'm available for support and improvements.",
  "We can add features one at a time, based on feedback.",
  "If you need a quick fix, just send me a message.",
  "I've worked with startups, agencies and established businesses.",
  "Each project is different, so I adapt the process to you.",
  "I'll be honest if I think something isn't worth building.",
  "My job is to make your work easier, not more complicated.",
  "Clear goals make for faster projects.",
  "Let's write the requirements down in plain language.",
  "I'll keep you updated every few days.",
  "If you're not sure yet, that's perfectly fine.",
  "We can explore the idea together before committing.",
  "Sometimes the best solution is surprisingly simple.",
  "I'll test it on real devices before release.",
  "Thanks again for trusting me with your project.",

  // Additional varied sentences
  "Technology should feel helpful, never confusing.",
  "Most problems become easier once you write them down.",
  "Learning never really stops in this field.",
  "I enjoy mentoring junior developers.",
  "Teaching others is the best way to learn.",
  "I've hosted more than fifty tech events.",
  "Community has always been important to me.",
  "Good teams share knowledge freely.",
  "Reading other people's code teaches you a lot.",
  "Every bug is a lesson in disguise.",
  "Simple code is easier to trust.",
  "Measure first, then optimise.",
  "Users notice speed more than features.",
  "Details make the difference.",
  "A clear error message can save hours of support.",
  "Write it once, and write it well.",
  "Documentation is a gift to your future self.",
  "Automate the boring parts, and focus on the interesting ones.",
  "The best feedback comes from real users.",
  "Ship early, learn fast, and keep improving.",

  // Second set: more conversation, explanation and everyday speech
  "Let's take a step back and look at the bigger picture.",
  "The first version should do one thing really well.",
  "I'll explain the trade offs, and you make the final call.",
  "We can always add more later, but removing features is harder.",
  "The dashboard shows today's orders, sales and stock at a glance.",
  "Customers can track their delivery without calling your team.",
  "Every message is saved, so nothing falls through the cracks.",
  "The system sends a reminder the day before each deadline.",
  "Your team will get a summary in Slack every morning.",
  "If a payment fails, the customer receives a friendly email.",
  "New sign ups are welcomed with a short tour of the app.",
  "The search understands typos and similar words.",
  "We can translate the interface into Urdu or Arabic later.",
  "The chatbot hands the conversation to a person when it should.",
  "Reports can be exported as spreadsheets or PDFs.",
  "Only managers can see the financial reports.",
  "Each user has their own secure login.",
  "Sensitive data is encrypted at rest and in transit.",
  "We keep a log of who changed what and when.",
  "The mobile app works on both small and large screens.",
  "Large buttons make the app easier to use on the go.",
  "Images load progressively, so nothing feels slow.",
  "Dark mode is easier on the eyes at night.",
  "We'll add analytics, so we know which screens people use.",
  "A short onboarding flow helps new users get started.",
  "The voice assistant can read out the latest updates.",
  "You can ask it questions in plain English.",
  "It remembers the conversation, so follow up questions work.",
  "If it isn't sure, it asks a clarifying question.",
  "The AI drafts the email, and you approve it before it's sent.",
  "Invoices are generated automatically at the end of the month.",
  "Low stock alerts go straight to your phone.",
  "The script checks for duplicates before saving anything.",
  "We reconcile the numbers every night, so reports always match.",
  "Your old data can be imported in a few minutes.",
  "There's no need to retrain your whole team.",
  "Most people learn the app in about ten minutes.",
  "I'll record a short video walkthrough for your staff.",
  "Support requests come to me directly, with no middlemen.",
  "Updates install automatically, without interrupting anyone.",
  "Let me show you a quick example.",
  "Imagine a customer messages you at midnight.",
  "Instead of waiting until morning, they get an answer right away.",
  "The answer comes from your own policies, not from guesswork.",
  "If the question is unusual, your team gets a notification.",
  "That's the kind of automation that pays for itself.",
  "Here's how the data flows through the system.",
  "First, the order arrives from the marketplace.",
  "Next, the stock level updates across every store.",
  "Then the customer receives a confirmation on WhatsApp.",
  "Finally, the courier is booked automatically.",
  "The whole process takes a few seconds.",
  "Before, it took someone twenty minutes per order.",
  "Now that person can focus on growing the business.",
  "I'd like to understand your workflow before suggesting anything.",
  "Could you show me the spreadsheet you use today?",
  "Which steps do you repeat every single day?",
  "Where do mistakes usually happen?",
  "What would you do with an extra hour each day?",
  "That's exactly the kind of task we can automate.",
  "Some tasks are better left to people, and that's fine.",
  "A good system supports your team instead of replacing them.",
  "We'll start with a pilot for one department.",
  "If it works well, we'll roll it out to everyone.",
  "Let's agree on how we'll measure success.",
  "Fewer support tickets would be a great sign.",
  "Faster replies to customers would be another.",
  "We'll review the results together after the first month.",
  "The weather was perfect for a long walk by the lake.",
  "He forgot his keys and had to wait outside.",
  "The shop on the corner sells the best samosas in town.",
  "We spent the afternoon reading in the shade.",
  "The bus driver smiled and wished everyone a good day.",
  "Her laugh filled the whole room.",
  "The baby finally fell asleep after midnight.",
  "A gentle breeze moved the curtains.",
  "The stars were unusually bright last night.",
  "They shared stories over a long dinner.",
  "The road was closed because of the snow.",
  "His car broke down halfway to the city.",
  "We found an old photograph in the drawer.",
  "The cricket match kept everyone glued to the screen.",
  "The mangoes this year are especially sweet.",
  "The guests arrived just as the food was ready.",
  "She practises the piano every afternoon.",
  "The wind carried the smell of rain.",
  "Our train leaves at a quarter past nine.",
  "The new bridge opened earlier than expected.",
  "He always keeps a notebook in his pocket.",
  "The village is quiet and peaceful in the evening.",
  "We bought fresh flowers for the table.",
  "The puzzle took the whole family two days to finish.",
  "A rainbow appeared after the storm.",
  "The coffee shop was full of students.",
  "The chef added a pinch of salt and a squeeze of lemon.",
  "The museum guide spoke softly and clearly.",
  "Every corner of the old city tells a story.",
  "The hikers reached the top just before sunset.",
  "We could hear the waves from our room.",
  "The tailor finished the suit in a single week.",
  "Why not try something different this time?",
  "How would you like to proceed?",
  "Would it help if I drew a quick diagram?",
  "Do you want me to handle the hosting as well?",
  "Shall I send the invoice to the same email address?",
  "Is there anything else on your mind?",
  "Would a weekly call suit you, or is email enough?",
  "Can I ask what made you choose this approach?",
  "What do your customers complain about most?",
  "How quickly do you need an answer?",
  "Oh, that's a clever solution!",
  "Ah, I see. That changes things a little.",
  "Yes! That's exactly right.",
  "No, I wouldn't recommend that, and here's why.",
  "Okay, let's do it.",
  "Hmm, let me check and get back to you.",
  "Well, there are a few options.",
  "Alright, I've noted that down.",
  "Brilliant, thank you!",
  "Sure, that's no trouble at all.",
  "Building software is a lot like building a house: the foundation matters most.",
  "The best tools are the ones your team actually enjoys using.",
  "Every line of code should earn its place.",
  "A little planning saves a lot of rework.",
  "When in doubt, ask the users.",
  "Simplicity is a feature.",
  "Good habits make good software.",
  "Progress beats perfection.",
  "Small improvements add up over time.",
  "I'm always happy to talk about a new idea.",
];
